version: '3'

networks:
  app:

services:
  php:
    image: php:8.2-fpm # Asegúrate de usar la versión que necesites
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./docker/php/www.conf:/etc/php8/php-fpm.d/www.conf:rw
      # - ./files/islas3/:/var/www/
      - ./:/var/www/html
    # ports:
    #   - 23771:2377
    depends_on:
      - database
    networks:
      - app
  nginx:
    image: nginx:stable-alpine
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    ports:
      - '8084:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app
    depends_on:
      - php

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-martin34}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    ports:
      - "5433:5432"
    networks:
      - app

###> doctrine/doctrine-bundle ###
###< doctrine/doctrine-bundle ###

