version: '3'

services:
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-martin34}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    ports:
      - "5433:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  php:
    user: "${UID:-1000}:${GID:-1000}"
    container_name: php_sanremo_api
    build:
      context: ./php
    ports:
      - '9009:9000'
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  nginx:
    container_name: nginx_sanremo_api
    image: nginx:stable-alpine
    ports:
      - '8087:80'
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

volumes:
  database_data:
